=== ashenm/mobile-partner/plugins/NetInfoUIExPlugin/TrendsCtrlProfile.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT TrendsCtrlProfile (Graphic, Text)>
<!ATTLIST TrendsCtrlProfile
	version CDATA #REQUIRED
>
<!ELEMENT Graphic (Color+)>
<!ELEMENT Color EMPTY>
<!ATTLIST Color
	id (ID_BACKGROUND1 | ID_BACKGROUND2 | ID_GRID | ID_TEXT | ID_PLOT1 | ID_PLOT2) #REQUIRED
	color CDATA #REQUIRED
>
<!ELEMENT Text (Font+)>
<!ELEMENT Font EMPTY>
<!ATTLIST Font
	id (ID_PLOT | ID_XUNITS | ID_YUNITS | ID_YRANGES) #REQUIRED
	family CDATA #REQUIRED
	style (Regular | Bold | Italic | BoldItalic | Underline | Strikeout) #REQUIRED
	size CDATA #REQUIRED
>

=== ashenm/mobile-partner/plugins/NetInfoUIExPlugin/TrendsCtrlProfile.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE TrendsCtrlProfile SYSTEM "TrendsCtrlProfile.dtd"><TrendsCtrlProfile version="1.0"><Graphic><Color id="ID_BACKGROUND1" color="#FF000000"/><Color id="ID_BACKGROUND2" color="#FF000000"/><Color id="ID_PLOT1" color="#B0EAEA00"/><Color id="ID_PLOT2" color="#B016D116"/><Color id="ID_GRID" color="#FF00EAEA"/><Color id="ID_TEXT" color="#FFFFFFFF"/></Graphic><Text><Font id="ID_PLOT" family="MS Shell Dlg" style="Regular" size="11"/><Font id="ID_XUNITS" family="MS Shell Dlg" style="Regular" size="11"/><Font id="ID_YUNITS" family="MS Shell Dlg" style="Regular" size="11"/><Font id="ID_YRANGES" family="MS Shell Dlg" style="Regular" size="11"/></Text></TrendsCtrlProfile>
